image:
  file: .gitpod.Dockerfile
tasks:
  - init: make build
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
vscode:
  extensions:
    - golang.go
    - ms-azuretools.vscode-docker
