name: ci
on:
  pull_request:
    branches:
      - main
      - release-*
    paths-ignore:
      - .github/workflows/ci.yml
      - Makefile
      - go.*
      - "**.go"

jobs:
  pull:
    strategy:
      matrix:
        arch: [amd64, arm64]
        job:
          - verify
          - build
          - unit-test
          - integration-test
    runs-on: ${{ fromJson('{"amd64":"ubuntu-latest", "arm64":["self-hosted", "Linux", "ARM64"]}')[matrix.arch] }}

    steps:
      - run: echo "Not required to run pull jobs."
